//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wintellect.Sterling.Core.Exceptions {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wintellect.Sterling.Core.Exceptions.Exceptions", typeof(Exceptions).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot purge when background operations are still running..
        /// </summary>
        internal static string BaseDatabaseInstance_Cannot_purge_when_background_operations {
            get {
                return ResourceManager.GetString("BaseDatabaseInstance_Cannot_purge_when_background_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed for type {0}: delete suppressed by trigger..
        /// </summary>
        internal static string BaseDatabaseInstance_Delete_Delete_failed_for_type {
            get {
                return ResourceManager.GetString("BaseDatabaseInstance_Delete_Delete_failed_for_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor can&apos;t be null.
        /// </summary>
        internal static string BaseDatabaseInstance_RegisterInterceptor_Interceptor_not_null {
            get {
                return ResourceManager.GetString("BaseDatabaseInstance_RegisterInterceptor_Interceptor_not_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save suppressed by trigger..
        /// </summary>
        internal static string BaseDatabaseInstance_Save_Save_suppressed_by_trigger {
            get {
                return ResourceManager.GetString("BaseDatabaseInstance_Save_Save_suppressed_by_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot truncate when background operations are still running..
        /// </summary>
        internal static string BaseDatabaseInstance_Truncate_Cannot_truncate_when_background_operations {
            get {
                return ResourceManager.GetString("BaseDatabaseInstance_Truncate_Cannot_truncate_when_background_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation {0} is not allowed. A Sterling engine is already active for this application. You must dispose the engine before activating a new one..
        /// </summary>
        internal static string SterlingActivationException {
            get {
                return ResourceManager.GetString("SterlingActivationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A definition for database with name {0} was not found..
        /// </summary>
        internal static string SterlingDatabaseNotFoundException {
            get {
                return ResourceManager.GetString("SterlingDatabaseNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database of type {0} has already been created. Only one database may exist..
        /// </summary>
        internal static string SterlingDuplicateDatabaseException {
            get {
                return ResourceManager.GetString("SterlingDuplicateDatabaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An index with the name {0} for type {1} already exists in Sterling database {1}..
        /// </summary>
        internal static string SterlingDuplicateIndexException {
            get {
                return ResourceManager.GetString("SterlingDuplicateIndexException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate definition for type {0} already exists in Sterling database {1}..
        /// </summary>
        internal static string SterlingDuplicateTypeException {
            get {
                return ResourceManager.GetString("SterlingDuplicateTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An index with the name {0} was not found for type {1}..
        /// </summary>
        internal static string SterlingIndexNotFoundException {
            get {
                return ResourceManager.GetString("SterlingIndexNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue accessing isolated storage: {0}. Check the inner exception for details..
        /// </summary>
        internal static string SterlingIsolatedStorageException {
            get {
                return ResourceManager.GetString("SterlingIsolatedStorageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to unregister the logger with id {0} failed. The logger was not found..
        /// </summary>
        internal static string SterlingLoggerNotFoundException {
            get {
                return ResourceManager.GetString("SterlingLoggerNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No table defintions were provided for the database. At least one table definition is required..
        /// </summary>
        internal static string SterlingNoTableDefinitionsException {
            get {
                return ResourceManager.GetString("SterlingNoTableDefinitionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed. Sterling is not activated. Call ISterlingDatabase.Activate() to prepare the database for use..
        /// </summary>
        internal static string SterlingNotReadyException {
            get {
                return ResourceManager.GetString("SterlingNotReadyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterling does not support serialization of NULL properties (property {0} on type {1})..
        /// </summary>
        internal static string SterlingNullException {
            get {
                return ResourceManager.GetString("SterlingNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization/deserialization failed because the serializer {0} could not process the type {1} requested..
        /// </summary>
        internal static string SterlingSerializerException {
            get {
                return ResourceManager.GetString("SterlingSerializerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A definition for type {0} was not found in Sterling database {1}..
        /// </summary>
        internal static string SterlingTableNotFoundException {
            get {
                return ResourceManager.GetString("SterlingTableNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterling trigger exception occurred for trigger {0}: {1}.
        /// </summary>
        internal static string SterlingTriggerException_SterlingTriggerException_Sterling_trigger_exception {
            get {
                return ResourceManager.GetString("SterlingTriggerException_SterlingTriggerException_Sterling_trigger_exception", resourceCulture);
            }
        }
    }
}
